blank_issues_enabled: true
contact_links:
  - name: "🔒 Security Report"
    url: https://github.com/GateNLP/ultimate-sitemap-parser/security/advisories/new
    about: Please report security vulnerabilities here